set BOOK_EXE=bin\book.exe
%BOOK_EXE% add "THE LORD OF THE RINGS" "TOLKIEN"
%BOOK_EXE% add "OLIVER TWIST" "DICKENS"
%BOOK_EXE% add "THE DAT OF THE JACKAL" "FORSYTH"
%BOOK_EXE% add "LORD OF THE FLIES" "GOLDING"
%BOOK_EXE% add "FRANKENSTEIN" "MARY SHELLEY"
%BOOK_EXE% add "VISUAL COBOL" "PAUL KELLY"
%BOOK_EXE% add "A BRIEF HISTORY OF TIME" "HAWKING"
%BOOK_EXE% add "DRACULA" "STOKER"
