set BOOK_EXE=bin\book.exe
%BOOK_EXE% add "THE LORD OF THE RINGS" "TOLKIEN" "FANTASY"
%BOOK_EXE% add "OLIVER TWIST" "DICKENS" "SERIAL"
%BOOK_EXE% add "THE DAT OF THE JACKAL" "FORSYTH" "THRILLER"
%BOOK_EXE% add "LORD OF THE FLIES" "GOLDING" "ALLEGORY"
%BOOK_EXE% add "FRANKENSTEIN" "SHELLEY" "HORROR"
%BOOK_EXE% add "VISUAL COBOL" "KELLY" "NON-FICTION"
%BOOK_EXE% add "A BRIEF HISTORY OF TIME" "HAWKING" "NON-FICTION"
%BOOK_EXE% add "DRACULA" "STOKER" "HORROR"
